<a href="https://colab.research.google.com/github/CopotronicRifat/CS-5783-Machine-Learning-Assignments/blob/main/ML_ASSIGNMENT_03_PROBLEM_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[7, 5, 0, 0, 3, 2],
                  [6, 4, 5, 1, 4, 8],
                  [9, 0, 2, 2, 5, 4],
                  [6, 3, 4, 7, 9, 8],
                  [7, 9, 0, 8, 2, 3]])

f = np.array([[1, 0, -1],
              [2, 0, -2],
              [1, 0, -1]])

**Problem 3.1:**

Dimention of the input is 6 * 6 * 1 and the kernel is 3*3.

**Number of parameters of the kernel** is 3*3 + 1.
That is 10.

**Problem 3.2:**

Output activation map after strided convolution applied.

In [ ]:
import numpy as np
from numpy.fft import fftn, ifftn

def strided_conv_2d(x, y, strides):
    s, t = strides
    # consensus dtype
    cdt = (x[0, 0, ...] + y[0, 0, ...]).dtype
    xi, xj = x.shape
    yi, yj = y.shape
    # round up modulo strides
    xk, xl, yk, yl = map(lambda a, b: -a//b * -b, (xi,xj,yi,yj), (s,t,s,t))
    # zero pad to avoid circular convolution
    xp, yp = (np.zeros((xk+yk, xl+yl), dtype=cdt) for i in range(2))
    xp[:xi, :xj] = x
    yp[:yi, :yj] = y
    # fold out strides
    xp = xp.reshape((xk+yk)//s, s, (xl+yl)//t, t)
    yp = yp.reshape((xk+yk)//s, s, (xl+yl)//t, t)
    # do conventional fft convolution
    xf = fftn(xp, axes=(0, 2))
    yf = fftn(yp, axes=(0, 2))
    result = ifftn(xf * yf.conj(), axes=(0, 2)).sum(axis=(1, 3))
    # restore dtype
    if cdt in (int, np.int_, np.int64, np.int32):
        result = result.real.round()
    return result.astype(cdt)

In [ ]:
print(strided_conv_2d(X, f, (1, 1)))

[[ 16   9  -4 -18  16  22   0 -28 -13]
 [ 17  -5 -10 -12  23  24   0 -30  -7]
 [ 18  -9 -15   1  25  23   0 -28 -15]
 [ 16  -2  -9   9  13  14   0 -20 -21]
 [  7   1  -2   5   2   3   0  -7  -9]
 [  0   0   0   0   0   0   0   0   0]
 [  7   5  -3  -2   3   2   0  -7  -5]
 [ 15  13  -5 -11  10  12   0 -20 -14]]


**Problem 3.3:**

Max pooling operation of size (2, 2).

In [ ]:
import numpy as np
import skimage.measure

In [ ]:
print(skimage.measure.block_reduce(X, (2,2), np.max))

[[7 5 8]
 [9 7 9]
 [9 8 3]]


**Documentation:**

Provided in the code.

Dimentions for both image and kernel is 2 as the depth of the Image and kernel if 1.

Output activation map of strided convolution is calculated with stride of 1. There is a function designed for the calculation.

Max pooling is applied on 2*2 window and calculated with an associated designed function.